### ISSUE TITLE
An edge case for String to Integer (atoi)

### ISSUE THREAD

**Issue by lexrus** [diwu/LeetCode-Solutions-in-Swift#1]
In case you ignored the requirements:

> The function first discards as many whitespace characters as necessary until the first non-whitespace character is found. Then, starting from this character, takes an optional **initial plus or minus sign** followed by as many numerical digits as possible, and interprets them as a numerical value.

Thus, `atoi("123-")` must be 123. But with your solution, the output is -123.

https://github.com/diwu/LeetCode-Solutions-in-Swift/blob/master/Solutions/Solutions/Easy/Easy_008_String_to_Integer_atoi.swift#L47

I think this is the proper answer:
https://github.com/haoel/leetcode/blob/master/algorithms/stringToIntegerAtoi/stringToIntegerAtoi.cpp#L51-L57

My translation in Swift:
https://github.com/lexrus/LeetCode.swift/blob/master/StringToIntegerAtoi/StringToIntegerAtoi.swift

**Comment by diwu** [comment]
Thanks for the edge case. Issue fixed in 8c9d9f5.
