### ISSUE TITLE
009_Palindrome_Number

### ISSUE THREAD

**Issue by lexrus** [diwu/LeetCode-Solutions-in-Swift#2]
What's the sense of initiating a extra Int `inputX`?
https://github.com/diwu/LeetCode-Solutions-in-Swift/blob/master/Solutions/Solutions/Easy/Easy_009_Palindrome_Number.swift#L29
I think `return palindromeX == x` just works.

**Comment by diwu** [comment]
Good catch. Fixed in 20d0661.
