### ISSUE TITLE
Easy_028_Implement_StrStr.swift, Brute Force Output Incorrect

### ISSUE THREAD

**Issue by camellk24** [diwu/LeetCode-Solutions-in-Swift#5]
The implementation of brute force will fail on haystakc: "mississippi" needle: "issispi"

Missing reset j = 0 on haystack[i+j] != needle[j]

**Comment by diwu** [comment]
Thanks @camellk24 . You are genius. Will update the code and the test cases soon.

**Comment by diwu** [comment]
Fixed in a913a22f213272b6218d23acace4704e70dd19ce
